name: dnmmrdr-spacectl
base: core24
version: 1.15.2
title: "Spacectl"
summary: Unofficial snap of the spacelift spacectl tool
description: |
  This is a unofficial snap of the spacelift.io tool spacectl
  spacectl allows user to communicate with the spacelift api
  through a convenient cli tool. This snap is NOT packaged
  by spacelift please do not report issues with this tool to there
  github page.
license: MIT

contact:
  - snap@drdisgust.com

issues:
  - https://github.com/dnmmrdr/spacectl-snap/issues

source-code:
  - https://github.com/dnmmrdr/spacectl-snap
  - https://github.com/spacelift-io/spacectl

website:
  - https://docs.spacelift.io/concepts/spacectl

grade: stable
confinement: strict

apps:
  spacectl:
    command: spacectl
    plugs:
      - network
      - network-bind
      - desktop

parts:
  spacectl:
    plugin: dump
    source-type: zip
    source: https://github.com/spacelift-io/spacectl/releases/download/v1.15.2/spacectl_1.15.2_linux_amd64.zip
